version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: web_app
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    networks:
      - web_network

networks:
  web_network:
    driver: bridge